version: '3.1'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo:/var/lib/odoo
      - ./log:/var/log/odoo
      - ./config:/etc/odoo
      - ./addons/modules:/mnt/extra-addons
